version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certresolver=myresolver"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=da-maltsev@inbox.ru"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--providers.docker.defaultRule=Host(`test.da-maltsev.ru`)"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - web
    restart: unless-stopped

  api:
    image: ghcr.io/da-maltsev/test-api:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`test.da-maltsev.ru`) && PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
    networks:
      - web
    restart: unless-stopped

  # ui:
  #   image: ghcr.io/da-maltsev/test-ui:latest
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.ui.rule=PathPrefix(`/`)"
  #     - "traefik.http.services.ui.loadbalancer.server.port=3000"
  #     - "traefik.http.routers.api.tls.certresolver=myresolver"
  #   networks:
  #     - web
  #   restart: unless-stopped

networks:
  web:
    driver: bridge

volumes:
  letsencrypt:
